models:
  yolov8_face_onnx: "models/yolov8_face.onnx"
  yolov8_face_hailo: "models/yolov8_face_hailo.hef"
  facenet_onnx: "models/facenet.onnx"
  facenet_hailo: "models/facenet_hailo.hef"

data:
  embeddings: "data/embeddings.json"
  registered_faces_dir: "data/registered_faces"
